# Generated by Django 5.2.4 on 2025-08-26 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ccapp", "0005_alter_rfq_subcontractor_alter_rfq_user_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("checked", "Checked"),
                ],
                default="created",
                max_length=20,
            ),
        ),
    ]
