# Generated by Django 5.2.4 on 2025-09-05 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ccapp", "0007_messagelist"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="messagelist",
            name="receiver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="received_messages",
                to="ccapp.chatuser",
            ),
        ),
        migrations.AlterField(
            model_name="messagelist",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="sent_messages",
                to="ccapp.chatuser",
            ),
        ),
    ]
