# Generated by Django 5.2.4 on 2025-09-05 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ccapp", "0008_chatuser_alter_messagelist_receiver_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="chat_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="chat_user_ref",
                to="ccapp.chatuser",
            ),
        ),
    ]
