# Generated by Django 5.2.4 on 2025-09-07 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ccapp", "0009_user_chat_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatuser",
            name="chat_id",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="chatuser",
            name="user_id",
            field=models.IntegerField(null=True),
        ),
    ]
