# Generated by Django 5.2.4 on 2025-10-07 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ccapp", "0012_bidding_biddingparticipant_bidding_subcontractors"),
    ]

    operations = [
        migrations.AddField(
            model_name="biddingparticipant",
            name="proposal",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="biddingparticipant",
            name="replied_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="biddingparticipant",
            name="replied_status",
            field=models.CharField(default="pending", max_length=20),
        ),
    ]
