# Generated by Django 5.2.4 on 2025-10-07 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ccapp", "0013_biddingparticipant_proposal_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="biddingparticipant",
            name="in_short_list",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="biddingparticipant",
            name="status",
            field=models.CharField(default="added", max_length=20),
        ),
    ]
