# Generated by Django 5.2.4 on 2025-10-08 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ccapp", "0014_biddingparticipant_in_short_list_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="biddingparticipant",
            name="mail_body",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="biddingparticipant",
            name="mail_subject",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="biddingparticipant",
            name="replied_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("replied", "Replied"),
                    ("rejected", "Rejected"),
                    ("accepted", "Accepted"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
